version: "3.9"
services:
  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    restart: always

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9093,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper
    restart: always

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ./.env.dev
    restart: always

  server:
    build:
      context: ./server
    volumes:
      - ./server:/server
      - /server/node_modules
    links:
      - mongo
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "dockerize -wait tcp://kafka:9093 -timeout 30s npm run dev"
    depends_on:
      - kafka
      - mongo
    restart: always

  client:
    build:
      context: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always

  analysis:
    build:
      context: ./analysis
    volumes:
      - ./analysis:/analysis
    depends_on:
      - kafka
    shm_size: "4gb"
            
  crawl:
    build:
      context: ./crawl
    volumes:
      - ./crawl:/crawl
    env_file:
      - ./.env.dev
    command: sh -c "dockerize -wait tcp://kafka:9092 -timeout 30s python3 -u crawl.py"
    depends_on:
      - kafka
      - mongo
    restart: always
