version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.8.14
    env_file:
      - .env.dev

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env.dev

  server:
    build:
      context: ./server
    volumes:
      - ./server:/server
    depends_on:
      - rabbitmq
    links:
      - mongo
    env_file:
      - ./.env.dev
    networks:
      - web_nw

  client:
    build:
      context: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    networks:
      - web_nw
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  web_nw:
    driver: bridge
