version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env.dev

  server:
    build:
      context: ./server
    volumes:
      - ./server:/server
      - /server/node_modules
    links:
      - mongo
    env_file:
      - ./.env.dev
    networks:
      - web_nw
    environment:
      - CHOKIDAR_USEPOLLING=true

  client:
    build:
      context: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    networks:
      - web_nw
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  web_nw:
    driver: bridge
